#!/bin/sh
#
# Loads a keyboard mapping
#

start() {
	printf "Loading keymap: "
	/usr/bin/loadkeys /etc/de-key.map
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo "Nothing to do."
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
