#!/bin/sh
#
# Loads console fonts
#

start() {
	printf "Loading console font: "
	/usr/bin/setfont -h12 /usr/share/consolefonts/lat1-12.psfu.gz
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo "Nothing to do."
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
